### ISSUE TITLE
safari下部分窗体打开位置偏移

### ISSUE THREAD

**Issue by MarvinWilliam** [gao-sun/x0popup#1]
safari下打开transform属性有点问题
看了下你的css,没有做兼容性处理...

**Comment by gao-sun** [comment]
@MarvinWilliam 谢谢反馈！我刚才也发现这个问题了，现在网站已更新应该OK了。
找出的原因居然是设置了页面上某些`<a>`的颜色会导致位置偏移，有点不能理解。

**Comment by MarvinWilliam** [comment]
@gao-sun 不应该吧,颜色的属性会影响形变属性么?

**Comment by gao-sun** [comment]
@MarvinWilliam 我在Safari上调试之后的结果是这样，而且是一个与窗体无关的颜色属性。
[Page](https://gao-sun.github.io/x0popup/)
如果把给这个页面上的`.content-wrapper .button`设置了color属性就会出现偏移的问题。(Safari版本9.1.1)没有做兼容性处理是因为在新版的浏览器上貌似显示都没有问题，而不用IE的用户大部分会自动更新吧。为了保险我会在更新中加一下，谢谢你啦！
