### ISSUE TITLE
Real Async rather than simulated?

### ISSUE THREAD

**Issue by mspanish** [gao-sun/x0popup#3]
Hi I need to actually do a validation of usernames against a DB. Is there a way to actually wait for this response to come back, rather than use a setTimeout to delay the button's execution? I'd like to use it inside of the inputValidator - but so far this seems to expect only a simple JS validation. Lovely library, by the way, thank you!

**Comment by gao-sun** [comment]
Hi, thank you for using my lib. I'm a little bit busy these days. I'll study JavaScript promise and add it to this lib. So could you please wait for several days? Thanks again.

**Comment by mspanish** [comment]
Hey thanks you are too kind, the library really is fantastic, I did use this code to simulate while I do my db lookup, and it's working fine, while a bit hacked up!

x0p({
    title: message,
    text: '',
    type: 'input',
    icon: 'info',
    inputValidator: function(button, value) {
        if(value == '')
            return 'Please write a name!';
       if (_.contains(value, ' '))
            return 'Pleae remove spaces!'
        return null;
    },
    animationType: 'fadeIn',
    buttons: [
        {
            type: 'cancel',
            key: 49,
        },
        {
          type: 'info',
              key: 50,
          text: 'submit',
           showLoading: true  
        }
    ]
}, function(button,value) {
    if(button == 'info') {
        // Simulate Delay
        saveGroupNameToDB(uid,value)
        setTimeout(function() {
          console.log('App.validator is '+ App.validator);
          if (App.validator)
            x0p('Great! your code is  \n\n'+value, null, 'ok', function(){
              // now you can do something like append their class code to their page, or ask them if they'd like to fill out some more information or something
            });
          else {
            x0p('User Name Taken!', null, 'error', function(button,value){
            //  console.log('error BUTTON = '+button);
                 createGroup(uid)
            });
          }
        }, 1500);
    }
});

**Comment by mspanish** [comment]
sorry the code styling didn't work for me here!

**Comment by gao-sun** [comment]
Hi thanks for your post. I can understand the code and it's an alternate way to implement asynchronous waiting. Actually I call another x0p() function on Ajax callback (jQuery) now. Anyway, thank you for feedback and please wait for me to finish the Promise feature.

**Comment by gao-sun** [comment]
Thank you for your advice and patient. Finally I implemented Promise on popup and input validator. Thanks again.
